mqtt-pa-adapter:
  broker-ip: "127.0.0.1"
  broker-port: 1883
  pa-properties:
    - intensity:
        topic: "sensor/intensity"
        type: int / string / double / boolean
        default: 0
    - temperature:
        topic: "sensor/state"
        type: json-field
        key: "state.temperature"
        field-type: int
        default: 0
    - humidity:
        topic: "sensor/state"
        type: json-field
        key: "state.humidity"
        field-type: float
        default: 0.0
    - last-temperatures:
        topic: "sensor/state"
        type: json-array
        key: "state.last_temperatures"
        field-type: int
        default: 0
    - state:
        topic: "sensor/state"
        type: json-object
        key: ["state.temperature", "state.humidity"]
        default: "{}"
  pa-actions:
    - turn-on:
        topic: actions/switch
        input: int
        output: string
    - turn-off:
        input: java-object
        output: json
  pa-event:
    - idem to properties



MqttPhysicalAdapterConfiguration.builder()   //("127.0.0.1", 1883)
.readFromConfig("config.yml")
.....
.build();


//Class builder

MqttPhysicalAdapterConfiguration readFromConfig(String path) {
  ....leggi il file
  if(type == int)
  this.addPhysicalAssetPropertyAndTopic("intensity", 0, "sensor/intensity", ConverterUtils.fromIntToInt)
}