brokerAddress: "127.0.0.1"
brokerPort: 1883
paProperties:
  - propertyKey: "last-temperatures"
    topic: "sensor/state"
    type: json-array
    key: "state.last_temperatures"
    field-type: int
    initialValue: 0
