brokerAddress: "127.0.0.1"
brokerPort: 1883
paProperties:
  - propertyKey: "last-temperatures"
    topic: "sensor/state"
    type: json-array
    key: "state.last_temperatures"
    fieldType: int
    initialValue:
      - 42
      - 3.14
      - Hello
      - true
